lint changes

diff --git a/.github/workflows/lint-go.yaml b/.github/workflows/lint-go.yaml
--- a/.github/workflows/lint-go.yaml
+++ b/.github/workflows/lint-go.yaml
@@ -18,21 +18,21 @@ jobs:
           go-version: '1.24'
           cache: false
 
-      - name: Check `builtins` directory
-        # if it has any changes in the 'builtins' dir after running `go generate`, echo an error and fail the workflow
+      - name: Check `stats/pos` directory
+        # if it has any changes in the 'stats/pos' dir after running `go generate`, echo an error and fail the workflow
         run: |
-          go generate ./builtin/gen
-          git diff --exit-code builtin/gen || (echo "\n\n\nbuiltin/gen directory is not up to date, run 'go generate ./...' to update it" && exit 1)
+          go generate ./stats/pos
+          git diff --exit-code stats/pos || (echo "\n\n\nstats/pos directory is not up to date, run 'go generate ./...' to update it" && exit 1)
 
-      - name: Check `modernize` (code style)
-        run: |
-          go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@v0.18.1 ./...
+      # TODO: Add this in a separate PR since it could modify plenty of files
+      # - name: Check `modernize` (code style)
+      #   run: |
+      #     go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@v0.18.1 ./...
 
       - name: golangci-lint
         uses: golangci/golangci-lint-action@v8
         with:
           version: v2.2.1
-          # use the default if on main branch, otherwise use the pull request config
-          args: --timeout=30m --config=.golangci.yml
+          args: --timeout=30m
           only-new-issues: false
           skip-cache: true
